### ISSUE TITLE
string-range pointers may not be updated properly

### ISSUE THREAD

**Issue by zmbq** [FrankensteinVariorum/fv-data#13]
Take a look at Spine_C08.xml. It's first string-range reference has the following xpath (I removed the problematic tei namespace):

`//zone[@type='main']//line[1]` in https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml . There is one big problem with this: 

There is more than one `<zone type="main">` in the document, which means this xpath *should* match all the second lines of all the zones. I write "should" because when I tried it out here (https://www.freeformatter.com/xpath-tester.html#ad-output) it didn't work. I had to change the XPath to:

`(//zone[@type='main']//line)[1]` and then I got all the second lines in all the main zones. 

For now I'm going to drop all string-range pointers and we'll continue working as if they don't exist. I hope we can find the time to add them back until the end of next week.

**Comment by zmbq** [comment]
I now see that in your old code, you didn't even try to parse the XPath, you just assumed the string-range XPath only contains surface, zone and line, and broke that into multiple XPath queries. That's why you haven't seen these issues before. I can do the same, but I still need to know which zone to reference.

**Comment by ebeshero** [comment]
@zmbq : @raffazizzi and I worked on a simple correction to help this morning. We didn't run into this problem yet because previously we were testing string pointing only in C10, but to get the XPath working we do need to provide the specific surface and zone identifier, so that, as you point out, you know *which* zone to be working in to locate the second line. The information is readily available in our code so we've just implemented that change in our pipeline. Let's take another look when I finish reprocessing the spine files. The XPath will now be more informative! 

This doesn't solve all the string pointing challenges, but let's see if it helps.

**Comment by ebeshero** [comment]
@zmbq I've now repaired the fv-data spine files and they will at least have more precise XPath locations to *one and only one* line in the target variorum file. Please take a look and see how these work now.

When I said earlier that this does not solve all the string pointing challenges, I was thinking about issues involving margin zones. There won't be many of those in this first group, and I think we can isolate them as a separate problem for now. Let's see how much these new pointers resolve problems.

**Comment by ebeshero** [comment]
## Left Margin Zones
@zmbq @raffazizzi  After Raff and I investigated today, we expect we're going to have trouble with some, but possibly not all, of the Left Margin Zone pointers, because we are lacking a bit of information in our XPaths to disambiguate *which* margin zone we're referring to when there is more than one present on an S-GA page surface. 

I'm closely inspecting our edition data and the S-GA files, and I see this isn't always the case: sometimes there is only one left-margin zone on a page--and I predict those pointers will be okay. But where we have *more than one*, we'd need to evaluate multiple possibilities to find a match--the same problem you were having, Itay, with our ambiguous pointers earlier. I want to see if we can stop that problem, but it's going to be a bit of intricate XSLT work--I'll see if I can do it. We want data from the `@corresp` attribute on the left-margin zone of a given SGA file, and we don't have that in our code right now. I am hoping that I can help with some XSLT right now by *locating* that code and *planting* it in our spine files. 

I think it might just be possible with some XSLT work on my part because:
1) I can query the collection of S-GA files and search for pages that hold multiple left-margin zones (and retrieve their `@corresp` attributes). I can also pull their text nodes.
2) I think I can find matching text in my collation output--I know I can find pages and left margin zones signaled there, and can evaluate with XSLT analyze-string to locate a match (I get to work with XSLT on this, which makes me happy, though it sounds like a parallel universe for programmatically evaluating the results of XPointers). Where I find a match, I'd like to find the first reference to left margin zone, and plant the value of the left-margin zone's `@corresp` there, so we have it in place.
3) Once I have it, I send it up the pipeline to generate the spine and we have more, better data for the pointing.

 I'm going to try this over this evening--wish me luck! (We'll need it.)

**Comment by ebeshero** [comment]
@raffazizzi @zmbq Well, it's good news, I think: I wrote some XSLT to do an identity transformation of our collation output data and try to locate `<anchor>` elements signaling margin locations in the S-GA files. These are always sitting in the main text zones to indicate a move to a specific margin zone. I can now locate the `@xml:ids` on these anchors and their parent `<line>` elements by count, thanks to the powers of XPath and `xsl:analyze-string`. What I want to do is pull in this data to *plant* it in our code just before a left-margin is signaled. Positioning the anchor information so it's available to you is the part I need to finish. 

I am thinking of planting the information like this in the TEI variorum-chunks : `<anchor xml:id="idToLeftMargin" loc="mainText-parentLine-number"/>`. Placement of the element is a little challenging (at least at the end of the day when I'm tired), but I think it'll come together in the morning.

**Comment by ebeshero** [comment]
```xml
<anchor xml:id="idToLeftMargin" loc="mainText-parentLine-number"/>
```

**Comment by ebeshero** [comment]
The other option I am afraid would be to go back to the MS files as I prepped them for collation and pull in the anchor elements there and then, and redo the collation. That is not a good option because we don’t have time for me to redo the collation editing to get those first 10 units into shape as we have them. So I am hoping I can get this XSLT patch to work.

**Comment by zmbq** [comment]
As I wrote yesterday, I'm not sure we'll even get to rendering these side notes, so certainly - don't spend time on this for now.

**Comment by ebeshero** [comment]
Ahh—as for rendering them, we were talking of “Google Docs style”—prioritizing the idea of tracking changes and holding the visual flow of text inline instead of trying to reproduce the illusion of margins. But that may be a story for another day. I almost have these anchors sorted out, so if it helps just to pull in more of them than we’ve been able to do so far, it might be worthwhile.
