### ISSUE TITLE
Pointers to non-existing documents

### ISSUE THREAD

**Issue by zmbq** [FrankensteinVariorum/fv-data#15]
Spines 9 and 10 seem to have pointers to non existing. For example 
`https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C09_app923.xml`

**Comment by ebeshero** [comment]
@raffazizzi I'm trying to figure out why we see this only in spine 9 and 10, and not in chunks 7 and 8 when the MS is present in the spine. Why would chunks 9 and 10 generate pointers with the app number appended at the end of the file name? I know it's something in P5_SpineGenerator.xsl, where we construct the file name, but I don't understand why (even when we ran that file this morning) we're generating file names like this for some chunks and not others. I'm investigating now, let me know if you can help--this is probably a simple fix.

**Comment by ebeshero** [comment]
AHA! I know why...easy one to fix. It's to do with my improperly matching on subchunked filenames, when C09 and C10 weren't subchunked. (C07 was.) Sorry for missing this--repairing! @zmbq @raffazizzi

**Comment by ebeshero** [comment]
Resolved in fv-postCollation with  https://github.com/PghFrankenstein/fv-postCollation/commit/e2d68f014a3fd2a58d898191ce0d8a63d13ff8f8 
Note: I need to address other issues before finishing the pipeline and replacing spine files in FV data. I'm just closing this ticket now because this particular issue is corrected in the pipeline.
