### ISSUE TITLE
Spine with no references to MS

### ISSUE THREAD

**Issue by zmbq** [FrankensteinVariorum/fv-data#17]
Since we will most likely not be able to handle MS, we need a Spine that has no references to MS at all. Right now we have a confusing set of data - sometimes an <app> just looks like there's no difference between all four editions, since the difference is with the invisible MS edition. This makes rendering very confusing.

Please provide me with a set of spines for each chunk that has no MS pointers or readings at all.

**Comment by ebeshero** [comment]
@zmbq I don't want to send you data that is inaccurate in the interests of display only. Rather than do that, I will revert my change this morning to the edit distances, even though that change was made for good reason. 

I was afraid you'd find this confusing, and you did.  The first several reading witnesses have only one pointer to the MS, indicating that it is **absent**. That made for a single value at the beginning that was the length of a passage--always a high intensity value. I decided that would be spurious to display as I was reviewing the data. The edit distance should show differences among the witnesses present. We can include an annotation and we have a graphic to explain why this is the case--indicating the locations where the MS witness is present vs. absent.

**Comment by ebeshero** [comment]
The problem with this, and the reason I made the change that you now find confusing, is that later on we see false high values in comparisons with no reading witness at all. The data is simply more accurate when we remove these false highs, and we don't necessarily need to signal high intensity of variance with an MS edition that is not present. If you can work with this data with this understanding, I would appreciate *not* reverting my change this morning.

**Comment by ebeshero** [comment]
@zmbq I'm deleting my comments because on re-reading, I realize this isn't about edit-distance at all. You're asking us to pretend as if our Variorum doesn't include the MS witness. I won't be doing that because this is a Variorum that is supposed to include five witnesses. All of our collation data is designed and shaped around the presence of the MS witness, even if you cannot find a way to display that witness.

**Comment by ebeshero** [comment]
@zmbq Anyway, it's not something I can just drop and do. I can't remove the fact that we collated five witnesses and generated locations of variance based on the presence or absence of that witness. That's not possible right now.

**Comment by zmbq** [comment]
Since I can’t show MS, we all must pretend it is not there. Because as far as the code is concerned – it really isn’t there. When you demo the system, MS will not be shown at all. Unless some miracle happens and I find the time to add it back. We are working practically around the clock as it is right now, I doubt it will happen.

 

  For now, until the XMLs are clean, I am removing chunks 7-10 (which just cause a crash when you try to open them). The display will be have a bit inconsistencies, I don’t think it’ll be too major, certainly not if you just ignore them in your presentation.

**Comment by ebeshero** [comment]
@zmbq I don't understand how or why you would need me to change the spine files when you can simply screen out the MS witness material yourself. It is misrepresenting our data to remove all references to the MS witness and I won't be doing that.

**Comment by ebeshero** [comment]
@zmbq This has nothing to do with display and everything to do with the variorum data we have been curating. Your display algorithm should be refined enough to read in what you can handle.

**Comment by ebeshero** [comment]
@zmbq Also, if I am understanding your issue, you are not even trying to display C07 to C10 where there is a lot of MS data present. If you're working with C01 - C06, there's a sort of ghost MS witness present by its absence. That's okay. In the spine data I pushed this morning for your use, I recalibrated the max edit-distances in awareness of the absence of the MS witness there, so *we are now only representing the max variance across the four present witnesses* where the MS is absent. I hope that helps you here.

**Comment by zmbq** [comment]
Elisa, I’m trying to get something out that you can present to people, in the very limited time we have. I’m asking for your help to patch the XML files, so that I don’t have to spend time on it. I’m doing the most to get something functional ready. Then, if there’s time, I can start working on the things that were left behind, starting with MS.

**Comment by ebeshero** [comment]
@zmbq If I remove all presence of fMS from the spine files, then we no longer are producing a Variorum that has anything to do with S-GA. There will be no going back to a state when we can work with S-GA data. Not only is it completely time consuming to re-collate all the files (this takes weeks and months) in the absence of S-GA data, but I can't do that after the years of work I have put into this project.

**Comment by zmbq** [comment]
OK, I think something I was misunderstood here. 

 

  You most certainly shouldn’t throw away all the hard work you’ve done. And even if *by next week* the system can’t handle MS, it *will* be able to handle MS a little later. What I’m asking is for you to do your XSLT magic, and make me *another set* of Spine files – one without MS reading or pointers. This can sit in another folder in the repo, or in another repo altogether. It will be a temporary measure, just until we get the code to work with MS.

**Comment by ebeshero** [comment]
@zmbq The thing is, *everything* is going to change even if I do that and you construct a reading view based on four witnesses, not five. Often a rdgGrp will contain only the MS witness with an altered word or phrase, and when that happens, when I remove it for your short-term makeshift interface, it is as if there never was any variance at all. I don't think I should be doing this because even a makeshift interface shouldn't be at odds with the collation data we have. 

If I understand what you're doing, and you're really only working with C01 - C06 to get something running, this shouldn't even matter because the MS witness is only sitting in the spine in the first app element anyway to signal its own absence. And the edit-distance data doesn't bother to signal variance against nothing in C01 - C06 at this point. Can you build with that?

**Comment by ebeshero** [comment]
@zmbq What happens is that I change the entire structure of the spine: many apps in C07 - C10 *should* entirely disappear with only four witnesses present because the spine is only supposed to represent moments of divergence among the editions. It's a fundamental alteration of our data. In C07 - C10, if I preserve the app and the four witnesses are in unison, the only thing we preserve is a ghost signal in the edit-distance with the manuscript. Do you want to keep that trace of difference via edit-distance metric? Or do you want to LOSE apps entirely that have any reference to solitary fMS variance?

**Comment by ebeshero** [comment]
@zmbq If we're displaying only four witnesses, I really want those witnesses still to carry their data about divergence from the fMS and from each other. That is, I want to make clear that even in displaying only four witnesses, I want those four witnesses to be expressing their variance with the missing fifth witness. For our presentation, we'll probably just be taking screen captures anyway. If we *could* present the fifth witness, we would and will, but I don't think it's a good idea to remove variant locations just because they can't be displayed in full right now. I hope that makes sense and we can proceed with the spine as it is.

**Comment by ebeshero** [comment]
In case the annotation sidebar is the issue: for now, it is better to leave a blank box for the fMS witness than to pretend that it isn't there for C07 - C10. And you could even fill it with the string of normalized tokens stored in the `@n` attribute on `<rdgGrp>`. It might not look pretty yet, but that's where we indicate it's a work in progress.

**Comment by ebeshero** [comment]
@zmbq Can we achieve a compromise here if I produce a temporary spine that leaves the apps alone, but just comments out the pointers to SGA files, and perhaps even replaces those pointers with the text content (drawn from normalized tokens) from the SGA witness at that point?

**Comment by ebeshero** [comment]
@zmbq I'm looking at the code here that references the fMS witness in spines C01 - C06. It's always the first `<app>`. This is what we have: 
```xml
  <app xml:id="C05_app1" n="137">
               <rdgGrp xml:id="C05_app1_rg1" n="['']">
                  <rdg wit="#fMS"/>
               </rdgGrp>
               <rdgGrp xml:id="C05_app1_rg2"
                       n="['letter', 'iv.to', 'mrs.', 'saville,', 'england.&lt;p/&gt;august', '5th,', '17—.&lt;p/&gt;&lt;p/&gt;so', 'strange', 'an', 'accident', 'has', 'happened', 'to', 'us,', 'that', 'i', 'cannot', 'forbear', 'recording']">
                  <rdg wit="#f1818">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1818_C05.xml#C05_app1-f1818__I"/>
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1818_C05.xml#C05_app1-f1818__F"/>
                  </rdg>
                  <rdg wit="#f1823">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1823_C05.xml#C05_app1-f1823__I"/>
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1823_C05.xml#C05_app1-f1823__F"/>
                  </rdg>
                  <rdg wit="#fThomas">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fThomas_C05.xml#C05_app1-fThomas__I"/>
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fThomas_C05.xml#C05_app1-fThomas__F"/>
                  </rdg>
                  <rdg wit="#f1831">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1831_C05.xml#C05_app1-f1831__I"/>
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1831_C05.xml#C05_app1-f1831__F"/>
                  </rdg>
               </rdgGrp>
            </app>
```

The app has an `@n` set to 137, indicating the whole length of the string in the other editions, but the MS is absent here. There is not pointer to the fMS in these witnesses to worry about--it's just empty. If I change these particular `@n` values to zero, does this help with the display?

**Comment by ebeshero** [comment]
@zmbq With this commit to update the main standoff_Spine files I might have met you halfway: https://github.com/PghFrankenstein/fv-data/commit/d64b4dcbcb0b7d3cfcf004f05248f352cd22a707

I updated the `app/@n` values to zero wherever we see a solitary empty MS witness and the other four witnesses are in unison. At that point the variance is simply zero now, and this should make things better for C01 to C06. 

I'll try making a temporary folder for commenting out the pointers to S-GA, which would only apply in C07 - C10. (There are no pointers to fMS in C01 to C06.)  I don't want to change the structure of the app elements in C07 - C10, though, so I'm just basically screening out the pointers here.

**Comment by ebeshero** [comment]
@zmbq With this commit https://github.com/PghFrankenstein/fv-data/commit/762b616b092023e0b962358fb1c2e0a7a8154983, I have now produced a temporary directory here in fv-data called `limited_Spine` which wraps all `<ptr>` elements inside `rdg[@wit='fMS']` in an XML comment, so they won't be trying to draw from fMS files in variorum-chunks.

I have purposefully not removed fMS entirely (about which see above). But I hope this serves your temporary purpose by suppressing calls to fMS as you're working with the spine files. 

I have done one more thing: I pulled the data about what text is actually present in fMS at this point and made it the body content of the `rdg[@wit='fMS']`. For an example, take a look at C08 here:
https://github.com/PghFrankenstein/fv-data/blob/master/limited_Spine/spine_C08.xml and a particular app with an fMS rdg: Here is how it is altered now:
 
```xml
 <app xml:id="C08a_app5" n="2">
               <rdgGrp xmlns:cx="http://interedition.eu/collatex/ns/1.0"
                       xml:id="C08a_app5_rg1"
                       n="['', 'seventeen']">
                  <rdg wit="#fMS"> seventeen
                     <!--<ptr target=https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fMS_C08.xml#string-range(//tei:surface[@xml:id='ox-ms_abinger_c56-0017']/tei:zone[@type='main']//tei:line[3],0,11)/>-->
                  </rdg>
               </rdgGrp>
               <rdgGrp xmlns:cx="http://interedition.eu/collatex/ns/1.0"
                       xml:id="C08a_app5_rg2"
                       n="['seventeen,']">
                  <rdg wit="#f1818">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1818_C08.xml#C08a_app5-f1818"/>
                  </rdg>
                  <rdg wit="#f1823">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1823_C08.xml#C08a_app5-f1823"/>
                  </rdg>
                  <rdg wit="#fThomas">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/fThomas_C08.xml#C08a_app5-fThomas"/>
                  </rdg>
                  <rdg wit="#f1831">
                     <ptr target="https://raw.githubusercontent.com/PghFrankenstein/fv-data/master/variorum-chunks/f1831_C08.xml#C08a_app5-f1831"/>
                  </rdg>
               </rdgGrp>
            </app>
```


None of this does much of anything to C01 - C06 since those files contain no calls out to fMS files. And we aren't so much erasing data as screening it off and even still revealing its text if we want to. I hope this is a workable compromise.

**Comment by ebeshero** [comment]
I updated the example code and the commit link above as I made a spot correction to the files.

**Comment by zmbq** [comment]
I'm closing this issue, for reasons that will become apparent in the next one.
