### ISSUE TITLE
multiply-defined ID

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-data#7]
in `P5-f1823_C06.xml` and  `P5-f1831_C10.xml` the id `F1823_v1_055` is defined multiple times, so I get a warning when trying to parse those files

**Comment by ebeshero** [comment]
Thanks @mdlincoln ! That's weird--it's an `@xml:id` on a `<pb/>` (marking a page-beginning, and the page number in the 1823 edition). There's two of those in close proximity, so they can't both be right. There will be an error in the XML source code...For right now (for your purposes) and I'll check which is the real page-beginning and comment out the bad one, but that's just a temporary patch. Let me know if you spot more like that! 

Note: Only the `@xml:id` attributes on `<seg>` elements mark a variant passage. I'm relieved this was on a page break, since it's likely to be a simple fix.

**Comment by ebeshero** [comment]
@mdlincoln I've fixed it for right now with this commit: https://github.com/PghFrankenstein/fv-data/commit/031a5ea34cdc64b2a14b332d7729590de41cbba3
Basically I checked the source photofacsimile for 1823 and noted the second `<pb>` was an error, so I commented it out here. I need to correct that earlier in the process, but for now this should help you continue processing.

**Comment by mdlincoln** [comment]
Great - this parses cleanly now.
