### ISSUE TITLE
reconstructing apps not in spine

### ISSUE THREAD

**Issue by mdlincoln** [FrankensteinVariorum/fv-data#8]
When an app is not referenced in the spine (e.g. `C01_app3`), does this mean that the app is identical across all witnesses?

I'm not sure how to reconstruct the different witnesses from the spine if we don't have references to _all_ apps in the spine.

**Comment by ebeshero** [comment]
@mdlincoln Yes--when the spine doesn't reference an `<app>` it's because there is no variance. C01_app3 can be seen in an earlier stage, when we output the collation here: https://github.com/PghFrankenstein/fv-postCollation/blob/master/P1-output/P1_C01.xml. To construct the spine files we remove it because at that point all five editions "flow together"--we don't need to refer to it as a hotspot of variance. (Also, sorry for the delay! I somehow missed seeing this issue earlier.)

**Comment by ebeshero** [comment]
@mdlincoln We don't change the app numbering, though, so you know that if the spine skips one or more numbers, those skipped over "speak with one voice"--just one `<rdgGrp>`. In the corresponding edition files, the contents of these unified `<app>`s come out as text without `<seg>` elements around them, since they don't need to be pointed to--there's no variance there.

**Comment by mdlincoln** [comment]
This seems to create a very unintuitive workflow if one wants to retrieve readings of apps. What I'm hearing so far:

1. Comprehensive list of app IDs for a chunk can only be found by ~picking one of the given witnesses of that chunk~ querying every possible app id across all witnesses ~and taking the unique set~ and then doing string matching to remove the witness id suffix for the `xml:id` attributes in each chunk and then taking the unique set, since some witnesses don't contain some apps
2. For each app id:
    - check the spine - if it exists there, then loop through reading groups -> readings -> pointers
    - If it does not exist there, then just get the reading from the original chunk and assume it is consistent across all witnesses

This puts the onus of logic processing onto the user, when instead this could be done once during the spine generation phase and then the end user would have a consistent and reliable interface to all the versions of the entire text via the spine. Would it introduce any issues to just include every app in the spine, even when there's just one reading group for the app and it's the same across all witnesses?

**Comment by mdlincoln** [comment]
I can also see a non-comprehensive spine causing challenges when you have different shapes of TEI like we're dealing with when trying to query the UMD TEI - how do I know what part of the UMD TEI belongs to a consistent app if that app is not in the spine, and thus I have no pointer and `target` query to use to navigate the UMD TEI?

**Comment by ebeshero** [comment]
@mdlincoln I am trying to figure out the issue for users here. When there is only one rdgGrp and all the witnesses align, we output the text of the edition. The spine exists to provide linking data about variant passages. If we have determined that passages agree, we don’t need targeted pointers at locations of unison. There is quite a lot of eventful variation going on here so that certainly our links are visiting every file of the UMD-TEI, multiple times.  The goal is NOT for the user to dynamically construct the variorum every time it loads—this is meant to be a stable interface—not freshly constituted from new collation processing every time a user visits. The spine is an index of variants meant to drive an interface that supplies information on variant passages. So I am not following why a user would be burdened by querying for apps not in the spine. We do have this as textual data and can make it available in an API, but I do not think it belongs in the spine since it doesn’t address information about variants.

**Comment by ebeshero** [comment]
Also, you would be expecting us to provide pointers to every single passage of the edition, not every passage that demonstrates variance. Why is this needed? If you want a “plain text” version of the editions we can supply files for that. We can also supply via API the passages themselves in each app, including the UMD-TEI, though this is resequenced for collation and not identical to the markup of the original files. Margin insertions to the left or right of the main text  were coded at the bottom of every page file, with a system of xml:ids and targets to indicate where they fit in semantic sequence. So my collation-resquenced version of UMD-TEI isn’t identical to the source files—and it is something adding complexity to the pointing algorithm in the spine. It is still navigable because of the xml:ids and targets in the source TEI, but it does introduce complexities. To address those, at an earlier stage of processing I am leaving a sort of breadcrumb trail of information in my resquenced UMD-TEI code that flags the resequenced passages and signals their margin zones to ease the work of pointer construction later. What I would like to know is why a user (not one of us on the project) would want or need pointers to every location in the UMD editions, and not just to every location that represents semantic variance? 

What is the gain of providing stand-off pointers to nonvariant passages in the variorum?

**Comment by ebeshero** [comment]
Finally, the spine is meant to be a series of stand-off pointers to variant locations and where they correspond with other editions. Since we are not outputting `<seg>` elements for nonvariant locations, we have not “seeded” the non-UMD editions with target ids for these locations, so currently at least our edition architecture isn’t designed for links to nonvariant locations. And from the added complexity of handling these, when we already have such a heavily populated interface, I do not see why we need or want this in the spine which drives the highlighting in the reading interface. Maybe we want it elsewhere? For someone checking our normalizing algorithm to see a passage we identified as nonvariant and how it aligns with the others, we can make this data available from the P1 files I showed you, built from the literal collation output. Perhaps we just need to distinguish the literal collation output from the spine which only indexes variant locations.

**Comment by ebeshero** [comment]
I guess a simpler answer to your issue here is that the spine files do not construct the editions—the spine is an output from the end of the process, after the source editions were reconstructed. The source editions are constructed in stages following collation. Collation requires processing XML markup as text strings, so its output needs to be carefully reprocessed to “raise” the flattened markup into a hierarchy for each edition. We do have our own in-house version of raised reconstructed SG-A (UMD-TEI) files, but they are not meant to replace the S-GA’s work. Our agreement here was to build bridges from our processing to variant locations in the S-GA archive, and provide a new view of its TEI in our interface.

**Comment by ebeshero** [comment]
@mdlincoln Sorry for one more on this thread, but here's one more wrinkle to consider for the S-GA (what you've been calling the UMD-TEI) files: They are "chunked" differently than our collation units and than our variorum navigation  (because each S-GA file represents one page of a handwritten notebook). So when we're displaying, say, a whole chapter, we're seeing not one but several S-GA files being displayed in sequence. We're able to do this because each reference to an S-GA location contains information about its source file--so we pull in the whole source file to get the nonvariant passages, and add highlighting to the variant ones based on the XPointers there.  I realize this is complicated, but we have, literally, something to prove by it--that we don't need to touch the source files if we can calculate and address the locations of each variant passage. I don't want to complicate that work by making it necessary to point to every *single* passage in S-GA. I could easily do that with the TEI edition files we've constructed for the other editions, just by planting a bunch of milestones  with `@xml:id`s or an alternate series of elements like the `<seg>` ones we're using, but if I did that we'd be adding a LOT more data to the files and yes, it would be a lot of work to reorganize the entire edition architecture. I wonder if we can more simply address this issue of locating and examining the nonvariant passages by making the `P1` files available, which *do* output the entire novel in `<app>` elements with flattened markup, and which do represent each `<app>` with its `@xml:id` in collation order.   Let me know what you think.

**Comment by mdlincoln** [comment]
@ebeshero thanks very much for these details, this clarifies the intent of the spine a lot - I realize now I was approaching it all backwards! 

I'm thinking of the use case (my use case, at the moment!) of trying to produce a synoptic table with all of the `app`s in your order.

>I wonder if we can more simply address this issue of locating and examining the nonvariant passages by making the P1 files available, which do output the entire novel in <app> elements with flattened markup, and which do represent each <app> with its @xml:id in collation order. Let me know what you think.

Yes, this format would be very useful - is this different from the current `P1` files in fv-postCollation? I see that those have escaped xml tags within them right now (e.g. `&lt;pb n="ix" xml:id="F1823_v1_016"/&gt;`) - if I were to remove those tags, would I then have a version of `P1` as you describe it here?

**Comment by ebeshero** [comment]
@mdlincoln Yes, *pretty much* with the caveat that the flattened tags are some of them very meaningful, indicating things like paragraph boundaries, or where a stanza of poetry begins, etc. If you were to try to turn those into real tags, though, they'd make broken XML since the collation splits up start and end tags just about everywhere. (A variant location quite frequently involves someone inserting a new paragraph break, which just accommodates the last words of one paragraph, a close tag, a start tag, and the first bit of the next paragraph--in other words, fragmented pieces of XML).

**Comment by ebeshero** [comment]
@mdlincoln Actually--I'm wrong there. You *could* just interpret these as real tags, because I made sure that they are self-closing, at this early stage pre- and post-collation. It's possible I didn't convert all the elements, though--I need to revisit the code.  But where I did convert to self-closing style, I've basically created a fragmented close and start tag: what we call a "Trojan end-marker" and "Trojan start-marker" (it's named after the Trojan horse and a pretty familiar practice for XML people who have to process their files as plain text sometimes). So all paragraph tags like like this: 
```
<p sID="ID1"/>
.......<!-- Paragraph contents -->.......
<p eID="ID1"/>  
<p sID="ID2"/>.....
<p eId="ID2"/>
```
With this,  I think I was planning that at SOME stage, a deliverable file for this project would contain up-converted, reconstructed markup of the edition that is compatible with the `<app>` hierarchy. P1 hasn't reconstructed these, but I think I have that in a later stage. Would you like a version with these self-closed tags left in place as meaningful markers? I think that's like P3 or something, but I'll go look for it...

**Comment by ebeshero** [comment]
@mdlincoln Okay--I revisited my directories from P1 through P5 in the postCollation repo. The answer to my own question is, no, I didn't produce a version of the `<app>` markup with reconstructed "trojan" markers inside. I also think if I did, I'd *still* run into broken XML hierarchy issues because of the complexities of the S-GA markup. We could try it--turn those escaped angle brackets into literal angle brackets and find out. I'm betting it'll break the hierarchy. If that is the case, yeah, the escaped tags may just be best left alone, or removed as you will for your synoptic table. 

In a very early stage of this project, I didn't think I could collate XML files, so we down-converted our files to a plain text markup system using square brackets and other symbols to indicate things like italics, paragraph breaks, etc. When I found out that we could process XML tags with collateX, I was relieved, and that told me something simple and profound about the nature of markup. Our system of signalling each other in a plain text document that a passage takes italics or is a header, or is part of a poem is no different than supplying that information with angle-bracket tags. In both cases we'd have to program something to read the tags eventually.

**Comment by mdlincoln** [comment]
Alright, this is also useful info. Thanks for these exhaustive explanations - it's really helping me wrap my head around the process you've gone through.

I agree that for this prototype synoptic visualization I'm trying to push out this week, I'll probably just remove the flattened tags from P1. However, it may eventually be useful to capture paragraph/stanza breaks etc for that visualization, if even in a slightly imperfect way, so I will definitely open an issue to return to that question at a later date.

Will those P1 files be remaining in the fv-postCollation repo for the foreseeable future? Just so that I know where to point my scripts for the time being...

**Comment by ebeshero** [comment]
@mdlincoln Yes--those files will stay in fv-postCollation. In future, I'll be adding more files to that directory as I continue refining the collation, but these are stable for a good while and the directory isn't moving.
